language: java
sudo: false
jdk:
- oraclejdk8
branches:
  only:
  - master
env:
  global:
    secure: bOm1mJB5pF94fCOFaF1NORPb5B6U9qnRyOdFbDtfUJygQZdtTfkGKMWS7TAXvyHuAghnsq4HkPjMMBf1ZCT8vvXd5mvbmXAc4dRPwv/WpF2uLTRsRuRTSYCREzGRslOFwaGCbfx03hQeRka/gZPewjP/0a0erA0Aa9jc12mETKt0J5kY996VxJW2pCCYszqHw1Q5pSf26nywC+k1eE9CapdJ6WP6dVJa2lDZYqNuP7STaoCKwrLdjRjCZrpbYX/pdOZLvrwG/iGPX8M09s68Ki021V+bC85xcDRB8xbABsEwUYyAtKypdZj+1KRZPVX6XbIbtUvJnyhx/IWfTpvnOFGxdjNlLRlcTRAm/MOxpcNo1DkfoMeOP6KHGCRjYyCq90+ifd+/M9+tH4GoC7zfbigofKDJij0GC7tDTwJ3zNyOKEENjoaAipMi37m5d4YzRvcaXTVaaXsaPwAKwbm8AC/ioEY7osTBgZd498n8x2Bhj7SOAcuyOSV69k+E+V49IgcpZoK6Cr7Tl891Bx5so6TXiCA/25EMzRG7jMJ5ahl3IsotcUUJSJW3eJxMXZjOxu1/UxFzbeKLoo7trA3feiXFYMpTtUsRfhCCDCWSfyaDf1rZC9FfqGxLYJrEF9xQcRkh67TIvzbgTB7mo1mgx/eA2xo0r5i2Kutyo2UnSvQ=

after_success:
  - mvn clean test jacoco:report coveralls:report