language: java
sudo: false
jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.m2


script:
  - mvn test
  - mvn jar:jar

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: USYD+BFrPd/MrLwqwAU4qoZD10tRkAP8CPnHlEnV09tJAlp6VWrNRww6uR63PHJZaygvpVEeqQnePHWuEm9t2fwXiRQEWozh+r6P+vrdkJF/9gT7IRX0LKpGwTcxGDxzmVeoTNi936eTVdYbcbBKObaP+1ZnhB34mfraz7wy6qG+PsLd15HB2k1+m5XLBL9AhfX4LloWxXKbVv99YyMBHMNNqsy7QHbDJ/mmXO9w+BIsETZDDE8hsqAmmnG5v+GSyD1fbbTPqpfwd8tFnm9FmozGbZyGyZBp9X9CsqQ3QUFLnvopOzfyICMJgk2HOqmuTkv5i/Ush2dlj7LYEFRND9fp/w3LLK2Oz9QJ70Ipa2bDOrTyXbYJ3pKECyrzZ5WyE7XRE6kbL4OozXulDsbA9h3E9D7OY1+/b9YFMhaBZazx/NZENwYE5LXdtkyeTL7Z3b2wawxePIlenkt4Nc8vEtLB9cLBiMRqxDmblpKFgrxVuZ7O5F6yYA0+lK8tRn5VCVmQGwS2Vm3lKI34n+eicTRw+rU23YB6voYGKk4Jsqu+94xHchtbmohdbmP9TqKkm5rbQspe50WIzuD35O91iX0ODINTom/Mw1tp2LjPZ0L2X9f0IZOTzzhPGXVnmZtJ8odXObH3+Wxt9CWPXTajFBXTVNu4qs7yxo3zQhI8xWs=
  file: target/sort-tool-1.0.jar
  on:
    repo: szpssky/sort-tool
    tags: true
    skip_cleanup: true
    all_branches: true
