language: java
sudo: false
jdk:
- oraclejdk8

env:
  global:
    secure: R2PGChtJiBa+gVVOk9097gTHGyBkgIHWyKcotd6yHHN14B01Bw+QxoG//z3DU1PhG2Sph1Z3iC9NxXFw9+B2+HbXc/egezZZWCQCyZXYqTRkS63bRwgjLYQg0khp3CKDeVTjQF3l0zqar8SdSyQBtrYR77yysAg7nC+VEu4YW2nE/XwVGDDIWKrmYq9683AQUwWOF77poXA/NfQW/tTgUmbwT+JjLa5jFv9v/2s3lBGv3f2gpmdq5cSSK5Q2y1tUHiFiQjHRxlOJcIkBDes9Z3503baWKACD7msYLyH49Crti47UAZb3LL9DSU9JFBgXNxqCXXUXTwYzB+MbT0ZIFdbvwvAKTROmz6PjzGQ9HLxGsgAbOS/mWx93NRyTwfU+DqRTdZc7jx7o+oss+DypGaut2jqXVxMRdA+b5lBa12eMjCxE6Xq0qBnmxNfuQl+uYQUPofnsGNxqxg5SA1duToNvk43Ejvv3PFPo/vojUFFKgNMs11Q9sH+fCmZaBU46a5g+7UOOK82ausm5h7y2tjnhwTMGXBKObEPaPVB63cbW1r6kJejD4hKbxHm1PC8q/VyptUJeTuQkDxL4u+EvDIpYu9KZ2ktHqrhzjNmdoF4dn/DCLXQPTIxZePa/6b61rckQOfSaoOh/1GV4nkxNEMphxHcKbYup+lQzj+EYvzk=
script:
  - mvn test
  - mvn jar:jar
after_success:
  - mvn clean test jacoco:report coveralls:report
deploy:
  provider: releases
  api_key:
    secure: USYD+BFrPd/MrLwqwAU4qoZD10tRkAP8CPnHlEnV09tJAlp6VWrNRww6uR63PHJZaygvpVEeqQnePHWuEm9t2fwXiRQEWozh+r6P+vrdkJF/9gT7IRX0LKpGwTcxGDxzmVeoTNi936eTVdYbcbBKObaP+1ZnhB34mfraz7wy6qG+PsLd15HB2k1+m5XLBL9AhfX4LloWxXKbVv99YyMBHMNNqsy7QHbDJ/mmXO9w+BIsETZDDE8hsqAmmnG5v+GSyD1fbbTPqpfwd8tFnm9FmozGbZyGyZBp9X9CsqQ3QUFLnvopOzfyICMJgk2HOqmuTkv5i/Ush2dlj7LYEFRND9fp/w3LLK2Oz9QJ70Ipa2bDOrTyXbYJ3pKECyrzZ5WyE7XRE6kbL4OozXulDsbA9h3E9D7OY1+/b9YFMhaBZazx/NZENwYE5LXdtkyeTL7Z3b2wawxePIlenkt4Nc8vEtLB9cLBiMRqxDmblpKFgrxVuZ7O5F6yYA0+lK8tRn5VCVmQGwS2Vm3lKI34n+eicTRw+rU23YB6voYGKk4Jsqu+94xHchtbmohdbmP9TqKkm5rbQspe50WIzuD35O91iX0ODINTom/Mw1tp2LjPZ0L2X9f0IZOTzzhPGXVnmZtJ8odXObH3+Wxt9CWPXTajFBXTVNu4qs7yxo3zQhI8xWs=
  file: target/sort-tool-1.0.jar
  on:
    repo: szpssky/sort-tool
    tags: true
    all_branches: true
